spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.2
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    # Pour voir les logs internes de ta propre appli
    fr.eletutour.virtualmj: DEBUG
    # C'est LA ligne qui manque souvent pour voir les payloads Ollama
    org.springframework.ai.ollama.api: DEBUG
    # Optionnel : Pour voir les entÃªtes HTTP globaux
    org.springframework.web.client.RestClient: DEBUG