spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral-small
          temperature: 0.7
    vectorstore:
      chroma:
        initialize-schema: true
